[workspace]
members = [
    "rmblast-lib",
    "rmblastn",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

[profile.release-debug]
inherits = "release"
debug = true

[workspace.dependencies]
rayon = "1.10"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
anyhow = "1"
memmap2 = "0.9"
