#!/usr/bin/env python3
"""Generate Rust data tables for the rmstats crate.

Sources:
  - blastn_values_* reward/penalty tables: parsed verbatim from NCBI
    blast_stat.c (no transcription by hand).
  - rmblast_*_values custom-matrix KA table: parsed verbatim from the
    RMBlast-patched blast_stat.c, then 30p53g (an explicit placeholder in the
    C source) is replaced with the real ALP fit and a new comparison.matrix
    entry is appended, both taken from fits/*.fit produced by alp-fit.

Output: rmstats/src/tables_data.rs
"""
import re, glob, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '../ncbi-blast-2.17.0+-src/c++/src/algo/blast/core/blast_stat.c')

src = open(SRC).read()


def _rustf(v):
    """Render a C numeric literal as a Rust f64 literal, value-preserving."""
    v = v.strip()
    if v == 'INT2_MAX':
        return '32767.0'
    f = float(v)
    return repr(f) if ('.' in repr(f) or 'e' in repr(f)) else repr(f) + '.0'


out = []
out.append('// GENERATED by gen_tables.py — do not edit by hand.')
out.append('// Data sources: NCBI blast_stat.c (verbatim) and ALP fits (fits/*.fit).')
out.append('')

# ---- blastn reward/penalty tables -------------------------------------------
# array_of_8 layout: {gap_open, gap_extend, lambda, K, H, alpha, beta, theta}
names = ['blastn_values_1_5','blastn_values_1_4','blastn_values_2_7',
         'blastn_values_1_3','blastn_values_2_5','blastn_values_1_2',
         'blastn_values_2_3','blastn_values_3_4','blastn_values_4_5',
         'blastn_values_1_1','blastn_values_3_2','blastn_values_5_4']
for name in names:
    m = re.search(r'static const array_of_8 %s\[\]\[8\] = \{(.*?)\};' % name, src, re.S) \
        or re.search(r'static array_of_8 %s\[\]\s*=\s*\{(.*?)\};' % name, src, re.S) \
        or re.search(r'const array_of_8 %s\[\]\s*=\s*\{(.*?)\};' % name, src, re.S) \
        or re.search(r'%s\s*\[\]\s*=\s*\{(.*?)\};' % name, src, re.S)
    if not m:
        sys.exit('cannot find table %s' % name)
    body = m.group(1)
    rows = re.findall(r'\{([^}]*)\}', body)
    out.append('pub static %s: &[[f64; 8]] = &[' % name.upper())
    for r in rows:
        vals = [v.strip() for v in r.split(',') if v.strip()]
        if len(vals) != 8:
            sys.exit('row in %s has %d values: %r' % (name, len(vals), r))
        fmt = ', '.join(_rustf(v) for v in vals)
        out.append('    [%s],' % fmt)
    out.append('];')
    out.append('')

# ---- rmblast custom-matrix table --------------------------------------------
# C layout: {open, extend, INT2_MAX, lambda, K, H, alpha, beta, C, alpha_v, sigma}
baked = {}
order = []
for m in re.finditer(r'static array_of_8 rmblast_(\w+)_values\[1\] = \{\s*\{([^}]+)\}', src):
    name, body = m.group(1), m.group(2)
    body = body.replace('(double) INT2_MAX', 'INT2_MAX')
    vals = [v.strip() for v in body.split(',')]
    baked[name] = vals
    order.append(name)

def read_fit(path):
    d = {}
    for line in open(path):
        parts = line.rstrip('\n').split('\t')
        d[parts[0]] = parts[1:]
    return d

# Replace the 30p53g placeholder and add comparison.matrix from the ALP fits.
fits = {os.path.basename(p)[:-4]: read_fit(p) for p in glob.glob(os.path.join(HERE, 'fits/*.fit'))}

def fit_row(fitname):
    f = fits[fitname]
    row = f['ncbi_row']  # open, extend, INT2_MAX, lambda, K, H, alpha, beta, C, alpha_v, sigma
    return [row[0], row[1], 'INT2_MAX'] + row[3:]

replaced = []
if '30p53g' in fits:
    baked['30p53g'] = fit_row('30p53g')
    replaced.append('30p53g')

new_entries = []
if 'comparison' in fits:
    new_entries.append(('comparison.matrix', fit_row('comparison')))

out.append('/// One row of the RMBlast custom-matrix KA table.')
out.append('/// Layout mirrors NCBI blast_stat.c rmblast_*_values:')
out.append('/// (matrix name, gap_open, gap_extend, lambda, K, H, alpha, beta, C, alpha_v, sigma)')
out.append('/// with the ALP mapping alpha = a_J + a_I, H = lambda/alpha, beta = b_J + b_I,')
out.append('/// alpha_v = Alpha_J + Alpha_I, sigma = Sigma.')
out.append('pub struct RmblastKaEntry {')
out.append('    pub name: &\'static str,')
out.append('    pub gap_open: i32,')
out.append('    pub gap_extend: i32,')
out.append('    pub lambda: f64,')
out.append('    pub k: f64,')
out.append('    pub h: f64,')
out.append('    pub alpha: f64,')
out.append('    pub beta: f64,')
out.append('    pub c: f64,')
out.append('    pub alpha_v: f64,')
out.append('    pub sigma: f64,')
out.append('}')
out.append('')
out.append('/// RMBlast matrix KA table. Entries for the 40 fitted RepeatMasker matrices are')
out.append('/// verbatim from the RMBlast-patched NCBI blast_stat.c; 30p53g (a placeholder in')
out.append('/// the C source) and comparison.matrix carry fresh ALP fits (see fits/).')
out.append('pub static RMBLAST_MATRIX_KA: &[RmblastKaEntry] = &[')

def emit(name_str, vals, comment=None):
    go, ge = vals[0], vals[1]
    lam, k, h, alpha, beta, c, alpha_v, sigma = vals[3:11]
    line = ('    RmblastKaEntry {{ name: "{n}", gap_open: {go}, gap_extend: {ge}, '
            'lambda: {lam}, k: {k}, h: {h}, alpha: {alpha}, beta: {beta}, '
            'c: {c}, alpha_v: {av}, sigma: {sig} }},').format(
        n=name_str, go=go, ge=ge, lam=_rustf(lam), k=_rustf(k), h=_rustf(h),
        alpha=_rustf(alpha), beta=_rustf(beta), c=_rustf(c), av=_rustf(alpha_v),
        sig=_rustf(sigma))
    if comment:
        out.append('    // ' + comment)
    out.append(line)

for name in order:
    comment = 'ALP refit (C source has a placeholder here)' if name in replaced else None
    emit(name + '.matrix', baked[name], comment)
for name_str, vals in new_entries:
    emit(name_str, vals, 'new entry, ALP fit (absent from the C table)')
out.append('];')
out.append('')

open(os.path.join(HERE, 'rmstats/src/tables_data.rs'), 'w').write('\n'.join(out) + '\n')
print('wrote rmstats/src/tables_data.rs: %d blastn tables, %d rmblast entries (%d replaced, %d new)'
      % (len(names), len(order) + len(new_entries), len(replaced), len(new_entries)))
