[package]
name = "rmblastn"
version = "3.0.9"
edition = "2021"
license = "CC0-1.0"

[[bin]]
name = "rmblastn"
path = "src/main.rs"

[features]
diagnostics = ["rmblast-lib/diagnostics"]

[dependencies]
rmblast-lib = { package = "rmblast-lib", path = "../rmblast-lib" }
clap = { workspace = true }
anyhow = { workspace = true }
rayon = { workspace = true }
