// GENERATED by gen_tables.py — do not edit by hand.
// Data sources: NCBI blast_stat.c (verbatim) and ALP fits (fits/*.fit).

pub static BLASTN_VALUES_1_5: &[[f64; 8]] = &[
    [0.0, 0.0, 1.39, 0.747, 1.38, 1.0, 0.0, 100.0],
    [3.0, 3.0, 1.39, 0.747, 1.38, 1.0, 0.0, 100.0],
];

pub static BLASTN_VALUES_1_4: &[[f64; 8]] = &[
    [0.0, 0.0, 1.383, 0.738, 1.36, 1.02, 0.0, 100.0],
    [1.0, 2.0, 1.36, 0.67, 1.2, 1.1, 0.0, 98.0],
    [0.0, 2.0, 1.26, 0.43, 0.9, 1.4, -1.0, 91.0],
    [2.0, 1.0, 1.35, 0.61, 1.1, 1.2, -1.0, 98.0],
    [1.0, 1.0, 1.22, 0.35, 0.72, 1.7, -3.0, 88.0],
];

pub static BLASTN_VALUES_2_7: &[[f64; 8]] = &[
    [0.0, 0.0, 0.69, 0.73, 1.34, 0.515, 0.0, 100.0],
    [2.0, 4.0, 0.68, 0.67, 1.2, 0.55, 0.0, 99.0],
    [0.0, 4.0, 0.63, 0.43, 0.9, 0.7, -1.0, 91.0],
    [4.0, 2.0, 0.675, 0.62, 1.1, 0.6, -1.0, 98.0],
    [2.0, 2.0, 0.61, 0.35, 0.72, 1.7, -3.0, 88.0],
];

pub static BLASTN_VALUES_1_3: &[[f64; 8]] = &[
    [0.0, 0.0, 1.374, 0.711, 1.31, 1.05, 0.0, 100.0],
    [2.0, 2.0, 1.37, 0.7, 1.2, 1.1, 0.0, 99.0],
    [1.0, 2.0, 1.35, 0.64, 1.1, 1.2, -1.0, 98.0],
    [0.0, 2.0, 1.25, 0.42, 0.83, 1.5, -2.0, 91.0],
    [2.0, 1.0, 1.34, 0.6, 1.1, 1.2, -1.0, 97.0],
    [1.0, 1.0, 1.21, 0.34, 0.71, 1.7, -2.0, 88.0],
];

pub static BLASTN_VALUES_2_5: &[[f64; 8]] = &[
    [0.0, 0.0, 0.675, 0.65, 1.1, 0.6, -1.0, 99.0],
    [2.0, 4.0, 0.67, 0.59, 1.1, 0.6, -1.0, 98.0],
    [0.0, 4.0, 0.62, 0.39, 0.78, 0.8, -2.0, 91.0],
    [4.0, 2.0, 0.67, 0.61, 1.0, 0.65, -2.0, 98.0],
    [2.0, 2.0, 0.56, 0.32, 0.59, 0.95, -4.0, 82.0],
];

pub static BLASTN_VALUES_1_2: &[[f64; 8]] = &[
    [0.0, 0.0, 1.28, 0.46, 0.85, 1.5, -2.0, 96.0],
    [2.0, 2.0, 1.33, 0.62, 1.1, 1.2, 0.0, 99.0],
    [1.0, 2.0, 1.3, 0.52, 0.93, 1.4, -2.0, 97.0],
    [0.0, 2.0, 1.19, 0.34, 0.66, 1.8, -3.0, 89.0],
    [3.0, 1.0, 1.32, 0.57, 1.0, 1.3, -1.0, 99.0],
    [2.0, 1.0, 1.29, 0.49, 0.92, 1.4, -1.0, 96.0],
    [1.0, 1.0, 1.14, 0.26, 0.52, 2.2, -5.0, 85.0],
];

pub static BLASTN_VALUES_2_3: &[[f64; 8]] = &[
    [0.0, 0.0, 0.55, 0.21, 0.46, 1.2, -5.0, 87.0],
    [4.0, 4.0, 0.63, 0.42, 0.84, 0.75, -2.0, 99.0],
    [2.0, 4.0, 0.615, 0.37, 0.72, 0.85, -3.0, 97.0],
    [0.0, 4.0, 0.55, 0.21, 0.46, 1.2, -5.0, 87.0],
    [3.0, 3.0, 0.615, 0.37, 0.68, 0.9, -3.0, 97.0],
    [6.0, 2.0, 0.63, 0.42, 0.84, 0.75, -2.0, 99.0],
    [5.0, 2.0, 0.625, 0.41, 0.78, 0.8, -2.0, 99.0],
    [4.0, 2.0, 0.61, 0.35, 0.68, 0.9, -3.0, 96.0],
    [2.0, 2.0, 0.515, 0.14, 0.33, 1.55, -9.0, 81.0],
];

pub static BLASTN_VALUES_3_4: &[[f64; 8]] = &[
    [6.0, 3.0, 0.389, 0.25, 0.56, 0.7, -5.0, 95.0],
    [5.0, 3.0, 0.375, 0.21, 0.47, 0.8, -6.0, 92.0],
    [4.0, 3.0, 0.351, 0.14, 0.35, 1.0, -9.0, 86.0],
    [6.0, 2.0, 0.362, 0.16, 0.45, 0.8, -4.0, 88.0],
    [5.0, 2.0, 0.33, 0.092, 0.28, 1.2, -13.0, 81.0],
    [4.0, 2.0, 0.281, 0.046, 0.16, 1.8, -23.0, 69.0],
];

pub static BLASTN_VALUES_4_5: &[[f64; 8]] = &[
    [0.0, 0.0, 0.22, 0.061, 0.22, 1.0, -15.0, 74.0],
    [6.0, 5.0, 0.28, 0.21, 0.47, 0.6, -7.0, 93.0],
    [5.0, 5.0, 0.27, 0.17, 0.39, 0.7, -9.0, 90.0],
    [4.0, 5.0, 0.25, 0.1, 0.31, 0.8, -10.0, 83.0],
    [3.0, 5.0, 0.23, 0.065, 0.25, 0.9, -11.0, 76.0],
];

pub static BLASTN_VALUES_1_1: &[[f64; 8]] = &[
    [3.0, 2.0, 1.09, 0.31, 0.55, 2.0, -2.0, 99.0],
    [2.0, 2.0, 1.07, 0.27, 0.49, 2.2, -3.0, 97.0],
    [1.0, 2.0, 1.02, 0.21, 0.36, 2.8, -6.0, 92.0],
    [0.0, 2.0, 0.8, 0.064, 0.17, 4.8, -16.0, 72.0],
    [4.0, 1.0, 1.08, 0.28, 0.54, 2.0, -2.0, 98.0],
    [3.0, 1.0, 1.06, 0.25, 0.46, 2.3, -4.0, 96.0],
    [2.0, 1.0, 0.99, 0.17, 0.3, 3.3, -10.0, 90.0],
];

pub static BLASTN_VALUES_3_2: &[[f64; 8]] = &[
    [5.0, 5.0, 0.208, 0.03, 0.072, 2.9, -47.0, 77.0],
];

pub static BLASTN_VALUES_5_4: &[[f64; 8]] = &[
    [10.0, 6.0, 0.163, 0.068, 0.16, 1.0, -19.0, 85.0],
    [8.0, 6.0, 0.146, 0.039, 0.11, 1.3, -29.0, 76.0],
];

/// One row of the RMBlast custom-matrix KA table.
/// Layout mirrors NCBI blast_stat.c rmblast_*_values:
/// (matrix name, gap_open, gap_extend, lambda, K, H, alpha, beta, C, alpha_v, sigma)
/// with the ALP mapping alpha = a_J + a_I, H = lambda/alpha, beta = b_J + b_I,
/// alpha_v = Alpha_J + Alpha_I, sigma = Sigma.
pub struct RmblastKaEntry {
    pub name: &'static str,
    pub gap_open: i32,
    pub gap_extend: i32,
    pub lambda: f64,
    pub k: f64,
    pub h: f64,
    pub alpha: f64,
    pub beta: f64,
    pub c: f64,
    pub alpha_v: f64,
    pub sigma: f64,
}

/// RMBlast matrix KA table. Entries for the 40 fitted RepeatMasker matrices are
/// verbatim from the RMBlast-patched NCBI blast_stat.c; 30p53g (a placeholder in
/// the C source) and comparison.matrix carry fresh ALP fits (see fits/).
pub static RMBLAST_MATRIX_KA: &[RmblastKaEntry] = &[
    RmblastKaEntry { name: "14p35g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.1241860392, k: 0.2565118357, h: 0.3349210581, alpha: 0.3707919708, beta: -4.9556787558, c: 1.0, alpha_v: 0.9227739447, sigma: 0.4531519888 },
    RmblastKaEntry { name: "14p37g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.1243509013, k: 0.2538327145, h: 0.3484386549, alpha: 0.3568803276, beta: -4.2557855073, c: 1.0, alpha_v: 0.8776725296, sigma: 0.4280544066 },
    RmblastKaEntry { name: "14p39g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.118108197, k: 0.2381799563, h: 0.3209988017, alpha: 0.3679396819, beta: -4.7872670508, c: 1.0, alpha_v: 0.9023682178, sigma: 0.438212301 },
    RmblastKaEntry { name: "14p41g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.1209164962, k: 0.251696198, h: 0.3474870514, alpha: 0.3479741064, beta: -4.1671740718, c: 1.0, alpha_v: 0.8383966803, sigma: 0.4086384478 },
    RmblastKaEntry { name: "14p43g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.1204338701, k: 0.2484920137, h: 0.3397421893, alpha: 0.35448606, beta: -4.6293999434, c: 1.0, alpha_v: 0.9246502826, sigma: 0.4497969208 },
    RmblastKaEntry { name: "14p45g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.1281012415, k: 0.2651519027, h: 0.3664022073, alpha: 0.3496191861, beta: -3.6832931705, c: 1.0, alpha_v: 0.676791766, sigma: 0.3297802745 },
    RmblastKaEntry { name: "14p47g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.116957149, k: 0.2334091021, h: 0.3226817428, alpha: 0.362453568, beta: -4.5920236604, c: 1.0, alpha_v: 0.8743834401, sigma: 0.4257435079 },
    RmblastKaEntry { name: "14p49g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.1167697593, k: 0.2289233061, h: 0.3136272703, alpha: 0.3723201723, beta: -5.1451440084, c: 1.0, alpha_v: 1.0683382337, sigma: 0.5198253075 },
    RmblastKaEntry { name: "14p51g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.1238779017, k: 0.2467119379, h: 0.32413383, alpha: 0.3821813407, beta: -4.7436611259, c: 1.0, alpha_v: 0.959347935, sigma: 0.4702766916 },
    RmblastKaEntry { name: "14p53g.matrix", gap_open: 29, gap_extend: 6, lambda: 0.1211022467, k: 0.2307304663, h: 0.2949314272, alpha: 0.4106115372, beta: -5.7396872323, c: 1.0, alpha_v: 1.1785051586, sigma: 0.5792624089 },
    RmblastKaEntry { name: "18p35g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.120477663, k: 0.2111410357, h: 0.2484902185, alpha: 0.4848386537, beta: -9.2182340936, c: 1.0, alpha_v: 2.1606541202, sigma: 1.0484662289 },
    RmblastKaEntry { name: "18p37g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.1213800379, k: 0.2057492194, h: 0.2637651575, alpha: 0.4601822282, beta: -7.8387763088, c: 1.0, alpha_v: 1.7397466038, sigma: 0.8478035267 },
    RmblastKaEntry { name: "18p39g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.1228853168, k: 0.2111281814, h: 0.2802003038, alpha: 0.4385623968, beta: -7.0578183141, c: 1.0, alpha_v: 1.4885560885, sigma: 0.7199586033 },
    RmblastKaEntry { name: "18p41g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.1096830298, k: 0.1715966796, h: 0.2171487218, alpha: 0.5051055742, beta: -11.745626606, c: 1.0, alpha_v: 2.7140718778, sigma: 1.3177448787 },
    RmblastKaEntry { name: "18p43g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.1179924113, k: 0.1957371364, h: 0.2544060456, alpha: 0.4637956264, beta: -8.6308911899, c: 1.0, alpha_v: 1.9654212688, sigma: 0.9528104325 },
    RmblastKaEntry { name: "18p45g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.1184247414, k: 0.2068045787, h: 0.2641082233, alpha: 0.4483947525, beta: -7.7015871289, c: 1.0, alpha_v: 1.7409388284, sigma: 0.8407473007 },
    RmblastKaEntry { name: "18p47g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.115878332, k: 0.1842046578, h: 0.2407688057, alpha: 0.4812846568, beta: -9.335095835, c: 1.0, alpha_v: 2.0412135907, sigma: 0.99896766 },
    RmblastKaEntry { name: "18p49g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.1248964218, k: 0.2141853759, h: 0.2675489103, alpha: 0.4668171575, beta: -7.449144315, c: 1.0, alpha_v: 1.7059257606, sigma: 0.8287060508 },
    RmblastKaEntry { name: "18p51g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.1106793836, k: 0.1621592148, h: 0.1979815532, alpha: 0.5590388692, beta: -12.8501033717, c: 1.0, alpha_v: 2.9575500576, sigma: 1.4379082677 },
    RmblastKaEntry { name: "18p53g.matrix", gap_open: 28, gap_extend: 5, lambda: 0.1082347513, k: 0.1408677318, h: 0.1771724651, alpha: 0.6109005213, beta: -15.3466248356, c: 1.0, alpha_v: 4.0564962157, sigma: 1.9697529516 },
    RmblastKaEntry { name: "20p35g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1112832877, k: 0.1466667286, h: 0.1741696491, alpha: 0.6389361652, beta: -16.1539210401, c: 1.0, alpha_v: 4.400482852, sigma: 2.1470674023 },
    RmblastKaEntry { name: "20p37g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1134511409, k: 0.1501236494, h: 0.193180875, alpha: 0.5872793615, beta: -13.588281838, c: 1.0, alpha_v: 3.4571364323, sigma: 1.6853854448 },
    RmblastKaEntry { name: "20p39g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1233401001, k: 0.1853070864, h: 0.2324952723, alpha: 0.5305058416, beta: -10.1409992518, c: 1.0, alpha_v: 2.3591423933, sigma: 1.1430502738 },
    RmblastKaEntry { name: "20p41g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1088138918, k: 0.1409300313, h: 0.1778018484, alpha: 0.611995279, beta: -15.585029525, c: 1.0, alpha_v: 4.1138777768, sigma: 1.9955787466 },
    RmblastKaEntry { name: "20p43g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1097495426, k: 0.1408421343, h: 0.1813610542, alpha: 0.6051439384, beta: -15.4307026893, c: 1.0, alpha_v: 3.8167291506, sigma: 1.8473169851 },
    RmblastKaEntry { name: "20p45g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1101110565, k: 0.1402262486, h: 0.1803401526, alpha: 0.6105742671, beta: -15.6260598026, c: 1.0, alpha_v: 4.0158358564, sigma: 1.941546144 },
    RmblastKaEntry { name: "20p47g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1198508511, k: 0.175230183, h: 0.2232474228, alpha: 0.536852115, beta: -10.4176260459, c: 1.0, alpha_v: 2.6779374226, sigma: 1.2941738959 },
    RmblastKaEntry { name: "20p49g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1150022018, k: 0.1500562415, h: 0.1891763921, alpha: 0.6079099011, beta: -13.5050176934, c: 1.0, alpha_v: 3.5156097791, sigma: 1.6995296741 },
    RmblastKaEntry { name: "20p51g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1101356126, k: 0.1310353805, h: 0.1457676446, alpha: 0.7555559595, beta: -21.3682588971, c: 1.0, alpha_v: 6.8421934749, sigma: 3.3156764005 },
    RmblastKaEntry { name: "20p53g.matrix", gap_open: 25, gap_extend: 5, lambda: 0.1239625969, k: 0.1752022586, h: 0.210665934, alpha: 0.588432095, beta: -10.5699570673, c: 1.0, alpha_v: 2.9893946322, sigma: 1.4621317927 },
    RmblastKaEntry { name: "25p35g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.0965155465, k: 0.0677355511, h: 0.0964040436, alpha: 1.0011566205, beta: -30.4001018883, c: 1.0, alpha_v: 12.8985688751, sigma: 6.316054612 },
    RmblastKaEntry { name: "25p37g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.0989264764, k: 0.076371967, h: 0.1025772304, alpha: 0.9644097036, beta: -28.8030585189, c: 1.0, alpha_v: 10.323863691, sigma: 5.496713931 },
    RmblastKaEntry { name: "25p39g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.1005843197, k: 0.0805691511, h: 0.1108913867, alpha: 0.9070525919, beta: -25.871656645, c: 1.0, alpha_v: 8.9465479422, sigma: 4.3181012869 },
    RmblastKaEntry { name: "25p41g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.1030661339, k: 0.0840485952, h: 0.1237017673, alpha: 0.8331823881, beta: -22.551467116, c: 1.0, alpha_v: 6.8660512763, sigma: 3.324559128 },
    RmblastKaEntry { name: "25p43g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.115543436, k: 0.1226554129, h: 0.1495157932, alpha: 0.7727841555, beta: -19.1049131656, c: 1.0, alpha_v: 6.6510170244, sigma: 3.2452511907 },
    RmblastKaEntry { name: "25p45g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.0973402625, k: 0.074202019, h: 0.1029029688, alpha: 0.9459422177, beta: -28.3361410207, c: 1.0, alpha_v: 11.0469248305, sigma: 5.390259264 },
    RmblastKaEntry { name: "25p47g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.0967346256, k: 0.0743885008, h: 0.0995494785, alpha: 0.9717240819, beta: -29.4199175933, c: 1.0, alpha_v: 10.5994502969, sigma: 5.1530785403 },
    RmblastKaEntry { name: "25p49g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.1070577141, k: 0.0941947942, h: 0.1181023643, alpha: 0.9064823958, beta: -24.6304665742, c: 1.0, alpha_v: 9.6077840749, sigma: 4.6858922905 },
    RmblastKaEntry { name: "25p51g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.1044972455, k: 0.0789036639, h: 0.1081508568, alpha: 0.9662174538, beta: -26.6415086581, c: 1.0, alpha_v: 10.6917212058, sigma: 5.2265052165 },
    RmblastKaEntry { name: "25p53g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.0977828435, k: 0.0607500307, h: 0.0834178835, alpha: 1.1722048, beta: -36.0114248393, c: 1.0, alpha_v: 16.235919638, sigma: 7.9627686727 },
    // ALP refit (C source has a placeholder here)
    RmblastKaEntry { name: "30p53g.matrix", gap_open: 22, gap_extend: 5, lambda: 0.1204393447, k: 0.1065198197, h: 0.1243912966, alpha: 0.9682296751, beta: -21.9319682594, c: 0.7246924929, alpha_v: 8.1529381219, sigma: 4.0254959683 },
    // new entry, ALP fit (absent from the C table)
    RmblastKaEntry { name: "comparison.matrix", gap_open: 20, gap_extend: 5, lambda: 0.09836223, k: 0.0789918084, h: 0.1116129577, alpha: 0.881279665, beta: -26.8400935093, c: 0.7198345171, alpha_v: 9.6806805374, sigma: 4.6681109347 },
];

